package com.my.greenDao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.my.greenDao.bean.Notify;

import com.my.greenDao.dao.NotifyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notifyDaoConfig;

    private final NotifyDao notifyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notifyDaoConfig = daoConfigMap.get(NotifyDao.class).clone();
        notifyDaoConfig.initIdentityScope(type);

        notifyDao = new NotifyDao(notifyDaoConfig, this);

        registerDao(Notify.class, notifyDao);
    }
    
    public void clear() {
        notifyDaoConfig.getIdentityScope().clear();
    }

    public NotifyDao getNotifyDao() {
        return notifyDao;
    }

}
